json.id favorited_plant.id
json.user_id favorited_plant.user_id
json.plant_api_id favorited_plant.plant_api_id
json.scientific_name favorited_plant.scientific_name
json.image_url favorited_plant.image_url
json.created_at favorited_plant.created_at
json.updated_at favorited_plant.updated_at